# Esta configuración la recibirán TODOS los servicios automáticamente
eureka:
  client:
    serviceUrl:
      defaultZone: http://logistica-eureka:8761/eureka/
  instance:
    prefer-ip-address: false # Para que use el nombre del servicio

# 🟢 NUEVO: Configuración global de Resiliencia para llamadas HTTP con Feign
feign:
  client:
    config:
      default: # Aplica a todos los Feign Clients del ecosistema
        connectTimeout: 2000 # 2 segundos máximo para establecer la conexión TCP
        readTimeout: 5000 # 5 segundos máximo para esperar la respuesta del servidor

spring:
  kafka:
    # Centralizamos Kafka aquí para que Service-Log y otros lo hereden de una vez
    bootstrap-servers: kafka:29092
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    hikari:
      data-source-properties:
        useSSL: false
        serverTimezone: UTC
        allowPublicKeyRetrieval: true
        createDatabaseIfNotExist: true

logging:
  file:
    name: /app/logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
      clean-history-on-start: false
  level:
    root: INFO
    com.logistica: DEBUG # Muestra tus controladores y servicios de todos los MS de forma segura

server:
  forward-headers-strategy: framework

app:
  gateway-url: http://localhost:9090

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
  override-with-generic-response: false
