server:
  port: ${PORT:8083}

spring:
  datasource:
    # CORREGIDO: Cambiado 'logistica-mysql' por 'mysql-db' para alinearse con el nombre del servicio en el compose.yml,
    # permitiendo que el DNS de Docker resuelva la conexión a la base de datos de forma correcta.
    url: jdbc:mysql://mysql-db:3306/db_service_users?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: app_user
    password: "1234"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    # Nota: bootstrap-servers se hereda del global, pero se mantiene la simetría explícita
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Conexión obligatoria para que el microservicio aparezca en Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

# Habilitar Actuator para los Healthchecks de Docker Compose
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

# Configuración de Logging adaptada a la estructura real del proyecto
logging:
  level:
    com.logistica.user: DEBUG
