server:
  port: ${PORT:8097}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

app:
  gateway-url: ${APP_GATEWAY_URL:http://api-gateway:8080}
