server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/users/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Para tener coherencia con compose.yaml. no olvidar agregar dependencia:mysql:condicion:healthy!
# Así con todos. Esta es una nota de recordartorio
