services:
  mysql-db:
    image: mysql:8.0
    container_name: logistica-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306" #el primer valor podría cambiarse para que windows lo use, pero internamente seguirá con 3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d #se deja para escalabilidad si en un futuro se agregan más .sql
    networks:
      - edificios-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Gestor de bbdd via web, para facilitar visual y funcionalidad (sin necesidad de instalar algún programa)
  adminer:
    image: adminer
    container_name: brm-adminer
    restart: always
    ports:
      - "8081:8080" #Para entrar debo poner mysql-db
    networks:
      - edificios-network


  eureka-server:
      build: ../../infraestructure/eureka-server # Docker lo compilará si hay un Dockerfile
      container_name: logistica-eureka
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
        interval: 10s
        timeout: 5s
        retries: 5
      ports:
        - "8761:8761"
      networks:
        - edificios-network
      environment:
        - SPRING_PROFILES_ACTIVE=docker

  # lentamente se agregarán más servicios en orden de encendido

networks:
  edificios-network:
    driver: bridge

volumes:
  mysql_data: