services:
  mysql-db:
    image: mysql:8.0
    container_name: logistica-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_service_auth
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - edificios-network

networks:
  edificios-network:
    driver: bridge

volumes:
  mysql_data: